---

- name: Deploy Django Site
  hosts: localhost
  vars:
    ami: ami-d732f0b7
  connection: local
  roles:
    - ec2_provisioning

# $ ansible-playbook -i plugins/inventory provision_ec2.yml --private-key=~/.ssh/*******.pem -e "repo_version=deployed" --ask-vault-pass
