remote_user: ubuntu
user_home: /home/ubuntu
django_home: "{{ user_home }}/checkout"
venv_home: "{{ user_home }}/venv"
django_settings_module: "imagersite.production"
rds_db_instance: "{{ db_name }}"
media_path: "{{ django_home }}/media"
static_path: "{{ django_home }}/static"
secret_key: "{{ secret_key }}"
system_packages :
  - build-essential
  - python-dev
  - postgresql-client
  - libpq-dev
  - python-pip
  - python-psycopg2
  - git
  - nginx
  - python-virtualenv
  - libjpeg-dev
  - libtiff-dev
  - libjpeg8-dev
  - zlib1g-dev
  - libfreetype6-dev
  - liblcms2-dev
  - libwebp-dev
  - tcl8.6-dev
  - tk8.6-dev

repo_version: deployed
