keypair: 401_banksd_key
security_group: ssh-access
instance_type: t2.micro
ami: ami-d732f0b7
vpc_subnet_id: subnet-29b9a46f
region: us-west-2
instance_tags: {"Name": "ansible-built"}
root_ebs_size: 8
zone: us-west-2c
instance_profile_name: mypoweruser
num_instances: 1
